server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Si no encuentra el archivo (ej. /ciudadano/agenda), redirige a index.html para que el router de React se haga cargo
        try_files $uri $uri/ /index.html;
    }

    # Configuración para servir archivos estáticos con cacheo agresivo, ya que no cambian frecuentemente
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        root /usr/share/nginx/html;
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}
